version: '2'
services:

  apache:
    image: rafaelcgstz/magento2
    # build: .
    ports:
        - "80:80" # web
        - "9001:9000" # xdebug
        - "2222:22" # ssh
        - "35729:35729" # live reload
    depends_on:
      - db
    links:
      - db
    volumes:
      - /var/www/html:/var/www/html
      # Example of my MacOS config
      # - /Users/rafaelcgstz/Public/Develop:/var/www/html
      - ~/.composer:/root/.composer
      - ~/.npm:/root/.npm
      - ~/.nvm:/root/.nvm
    environment:
      XDEBUG_CONFIG: "remote_host=dev.local"
      PHP_IDE_CONFIG: "serverName=Docker"

  db:
    image: mariadb
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    volumes:
        - /var/lib/mysql # database files
